### ISSUE TITLE
能给readme里的图片链接提个建议吗?

### ISSUE THREAD

**Issue by hamxiaoz** [lepture/yue.css#13]
可否换成safe for work的? 我工作时看到这个真心尴尬. 我知道虽然是艺术...

**Comment by lepture** [comment]
@hamxiaoz 可以这个图一点都不色呀

**Comment by supergrubby** [comment]
@hamxiaoz 也许几十年后，就不会那么尴尬了。

**Comment by greatghoul** [comment]
感觉现在的图片很棒。

**Comment by hamxiaoz** [comment]
@supergrubby 可能是我个人的原因吧. 大家觉得可以就好.
